version: '3.8'

services:
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/server
    environment:
      - PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
